src/config/urls.py
from django.contrib import admin

from django.urls import path, include

from core.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("user/", include("core.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
    path("baton/", include("baton.urls")),
]

src/core/urls.py
from django.urls import path

from core.views import UserLogin, UserLogout, UserRegistration, ActivateUser, UserProfileView
from students.views import search_history

app_name = "core"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/", UserProfileView.as_view(), name="profile_user"),
    path("history/", search_history, name="history"),
]

src/students/urls.py
from django.urls import path

from students.views import (
    CreateStudentView,
    UpdateStudentView,
    DeleteStudentView,
    GetStudentsView,
)

app_name = "students"

urlpatterns = [
    path("", GetStudentsView.as_view(), name="get_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
import datetime

import random

from uuid import uuid4

from django.core.validators import MinLengthValidator

from django.db import models

from faker import Faker

from groups.models import Group

from core.utils.student_validators import first_name_validator, grade_validator


class Students(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid4, unique=True, db_index=True)
    first_name = models.CharField(max_length=120, null=True, validators=[MinLengthValidator(2), first_name_validator])
    last_name = models.CharField(max_length=120, null=True, validators=[MinLengthValidator(2)])
    email = models.EmailField(max_length=120, null=True)
    grade = models.PositiveIntegerField(default=0, null=True, validators=[grade_validator])
    birth_date = models.DateField(null=True)
    department = models.CharField(max_length=300, null=True)
    group = models.ForeignKey(to=Group, related_name="all_students_in_this_group", on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="static/img/", blank=True, null=True)
    summary = models.FileField(upload_to="files/", blank=True, max_length=200)

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "All students"
        ordering = (
            "-first_name",
            "last_name",
        )

    def age(self):
        return datetime.datetime.now().year - self.birth_date.year

    def __str__(self):
        return f"{self.first_name}_{self.last_name} ({self.grade})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                grade=random.randint(1, 11),
                birth_date=faker.date_time_between(start_date="-30y", end_date="-18y"),
            )

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Students


class StudentForm(ModelForm):
    class Meta:
        model = Students
        fields = ("first_name", "last_name", "email", "grade", "birth_date", "department", "group")

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email:
            raise ValidationError("Yandex domain is forbidden in our country!!!")

        return email

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name cant be equal")

        return cleaned_data

src/students/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Q

from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView

from students.forms import StudentForm

from students.models import Students

from webargs import fields

from webargs.djangoparser import use_kwargs


class GetStudentsView(LoginRequiredMixin, TemplateView):
    template_name = "students/students_list.html"
    model = Students

    @use_kwargs(
        {
            "first_name": fields.Str(required=False),
            "last_name": fields.Str(required=False),
            "search_text": fields.Str(required=False),
        },
        location="query",
    )
    def get(self, request, **kwargs):
        students = Students.objects.all()

        search_fields = ["first_name", "last_name", "email"]

        for field_name, field_value in kwargs.items():
            if field_name == "search_text":
                request.session[f"search_text_{datetime.datetime.now()}"] = field_value

                or_filter = Q()

                for field in search_fields:
                    # accumulate filter condition
                    or_filter |= Q(**{f"{field}__contains": field_value})

                students = students.filter(or_filter)

            else:
                if field_value:
                    students = students.filter(**{field_name: field_value})

        return render(request, template_name="students/students_list.html", context={"students": students})


def search_history(request):
    log_list = {}
    for key, value in request.session.items():
        if "search_text" in key:
            log_list.update({key: value})

    return render(request, template_name="search_history.html", context={"search_history": log_list})


class CreateStudentView(LoginRequiredMixin, CreateView):
    template_name = "students/students_create.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")
    initial = {"grade": 1}


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    template_name = "students/students_update.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")
    pk_url_kwarg = "uuid"
    queryset = Students.objects.all()


class DeleteStudentView(LoginRequiredMixin, UpdateView, DeleteView):
    template_name = "students/students_delete.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")
    pk_url_kwarg = "uuid"
    queryset = Students.objects.all()

src/templates/students/students_create.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button  type="submit" class="my-button btn-shine" value="Create">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/students/students_delete.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button class="my-button btn-shine" type="submit" value="Delete">Delete</button>
        </form>
    </div>
{% endblock %}

src/templates/students/students_list.html
{% extends "index.html" %}
{% load static %}


{% block content %}

    <link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <table class="table table-bordered border-primary">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Grade</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Department</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <th><img src="
                    {% static 'img/avatar2.jpeg' %}" width="32" height="36" alt="..."
                ></th>
                <th>{{ student.first_name }}</th>
                <th>{{ student.last_name }}</th>
                <th>{{ student.email }}</th>
                <th>{{ student.grade }}</th>
                {% if student.birth_date %}
                    <th>{{ student.birth_date }}</th>
                    <th>{{ student.age }}</th>
                {% else %}
                    <th>Undefined</th>
                    <th>Undefined</th>
                {% endif %}
                {% if student.department %}
                    <th>{{ student.department }}</th>
                {% else %}
                    <th>Empty department</th>
                {% endif %}
                <th>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}">
                        Delete
                    </a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/templates/students/students_update.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button class="my-button btn-shine" type="submit" value="Update">Update</button>
        </form>
    </div>
{% endblock %}