src/config/urls.py
from django.contrib import admin

from django.urls import path, include

from core.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("user/", include("core.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
    path("baton/", include("baton.urls")),
]

src/core/urls.py
from django.urls import path

from core.views import UserLogin, UserLogout, UserRegistration, ActivateUser, UserProfileView
from students.views import search_history

app_name = "core"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/", UserProfileView.as_view(), name="profile_user"),
    path("history/", search_history, name="history"),
]

src/groups/urls.py
from django.urls import path

from groups.views import GetGroupView, CreateGroupView, UpdateGroupView, DeleteGroupView, GetGroupsTeachersView

app_name = "groups"

urlpatterns = [
    path("", GetGroupView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("get-groups-teachers/<int:pk>/", GetGroupsTeachersView.as_view(), name="get_groups_teachers"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import CreateTeacherView, UpdateTeacherView, DeleteTeacherView, GetTeacherView

app_name = "teachers"

urlpatterns = [
    path("", GetTeacherView.as_view(), name="get_teachers"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
import random

from django.core.validators import MinLengthValidator
from django.db import models

from faker import Faker

from core.utils.teacher_validators import (
    teacher_first_name_validator,
    teacher_last_name_validator,
    teacher_experience_years_validator,
)


class Teacher(models.Model):
    first_name = models.CharField(
        max_length=120, null=True, validators=[MinLengthValidator(2), teacher_first_name_validator]
    )
    last_name = models.CharField(
        max_length=120, null=True, validators=[MinLengthValidator(2), teacher_last_name_validator]
    )
    email = models.EmailField(max_length=120, null=True)
    experience_years = models.PositiveIntegerField(
        default=3, null=True, validators=[teacher_experience_years_validator]
    )
    birth_date = models.DateField(null=True)
    subject = models.CharField(max_length=120, null=True)
    group = models.ManyToManyField(to="groups.Group")
    avatar = models.ImageField(upload_to="static/img/", blank=True, null=True)

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "All teachers"

    def __str__(self):
        return f"{self.pk} {self.first_name}_{self.last_name} ({self.subject})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        subject = [
            "PE",
            "Math",
            "Chemistry",
            "Art",
            "History",
            "Music",
            "English",
            "Geography",
        ]

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                experience_years=random.randint(3, 7),
                birth_date=faker.date_time_between(start_date="-55y", end_date="-30y"),
                subject=random.choice(subject),
            )

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ("first_name", "last_name", "email", "experience_years", "birth_date", "subject", "group")

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email:
            raise ValidationError("Yandex domain is forbidden in our country!!!")

        return email

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name cant be equal")

        return cleaned_data

    def clean_subject(self):
        return self.cleaned_data["subject"].capitalize()

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView

from webargs import fields

from webargs.djangoparser import use_kwargs

from teachers.forms import TeacherForm

from teachers.models import Teacher


class GetTeacherView(LoginRequiredMixin, TemplateView):
    template_name = "teachers/teachers_list.html"
    model = Teacher

    @use_kwargs(
        {
            "first_name": fields.Str(required=False),
            "last_name": fields.Str(required=False),
            "search_text": fields.Str(required=False),
        },
        location="query",
    )
    def get(self, request, **kwargs):
        teachers = Teacher.objects.all()

        search_fields = ["first_name", "last_name", "subject"]

        for field_name, field_value in kwargs.items():
            if field_name == "search_text":
                or_filter = Q()

                for field in search_fields:
                    or_filter |= Q(**{f"{field}__contains": field_value})

                teachers = teachers.filter(or_filter)

            else:
                if field_value:
                    teachers = teachers.filter(**{field_name: field_value})

        return render(request, template_name="teachers/teachers_list.html", context={"teachers": teachers})


class CreateTeacherView(LoginRequiredMixin, CreateView):
    template_name = "teachers/teachers_create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    template_name = "teachers/teachers_update.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")
    queryset = Teacher.objects.all()


class DeleteTeacherView(LoginRequiredMixin, UpdateView, DeleteView):
    template_name = "teachers/teachers_delete.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")
    queryset = Teacher.objects.all()

src/templates/teachers/teachers_create.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button  type="submit" class="my-button btn-shine" value="Create">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/teachers/teachers_delete.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}



{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button class="my-button btn-shine" type="submit" value="Delete">Delete</button>
        </form>
    </div>
{% endblock %}

src/templates/teachers/teachers_list.html
{% extends "index.html" %}
{% load static %}


{% block content %}

<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <table class="table table-bordered border-primary">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Experience years</th>
            <th scope="col">Birth date</th>
            <th scope="col">Subject</th>
            <th scope="col">Group</th>
            <th scope="col">To groups</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <th><img src="
                    {% static 'img/avatar.png' %}" width="60" height="36"  alt="..."
                ></th>
                <th>{{ teacher.first_name }}</th>
                <th>{{ teacher.last_name }}</th>
                <th>{{ teacher.email }}</th>
                <th>{{ teacher.experience_years }}</th>
                {% if teacher.birth_date %}
                    <th>{{ teacher.birth_date }}</th>
                {% else %}
                    <th>Undefined</th>
                {% endif %}
                <th>{{ teacher.subject }}</th>
                <th>{% for group in teacher.group.all %} {{ group.faculty }}{% endfor %}</th>
                 <th scope="col"> {% for group in teacher.group.all %}
                     <a type="button" class="btn btn-primary"
                            href="{% url 'groups:get_groups_teachers' group.pk %}">{{ group.id }}</a>
                    {% endfor %}
                <th>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                    href="{% url 'teachers:delete_teacher' teacher.pk %}">Delete</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/templates/teachers/teachers_update.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}



{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button class="my-button btn-shine" type="submit" value="Update">Update</button>
        </form>
    </div>
{% endblock %}