src/config/urls.py
from django.contrib import admin

from django.urls import path, include

from core.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("user/", include("core.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
    path("baton/", include("baton.urls")),
]

src/core/urls.py
from django.urls import path

from core.views import UserLogin, UserLogout, UserRegistration, ActivateUser, UserProfileView
from students.views import search_history

app_name = "core"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/", UserProfileView.as_view(), name="profile_user"),
    path("history/", search_history, name="history"),
]

src/groups/urls.py
from django.urls import path

from groups.views import GetGroupView, CreateGroupView, UpdateGroupView, DeleteGroupView, GetGroupsTeachersView

app_name = "groups"

urlpatterns = [
    path("", GetGroupView.as_view(), name="get_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("get-groups-teachers/<int:pk>/", GetGroupsTeachersView.as_view(), name="get_groups_teachers"),
]

src/groups/models.py
import random

from django.core.validators import MaxLengthValidator

from django.db import models

from faker import Faker

from core.utils.groups_validators import amount_students_validator


class Group(models.Model):
    group_name = models.CharField(max_length=120, null=True, validators=[MaxLengthValidator(2)])
    amount_students = models.PositiveIntegerField(default=30, null=True, validators=[amount_students_validator])
    head_teacher = models.CharField(max_length=120, null=True)
    faculty = models.CharField(max_length=120, null=True)
    head_teacher_email = models.EmailField(max_length=120, null=True)
    head_teacher_phone = models.CharField(max_length=120, null=True)

    class Meta:
        verbose_name = "Groups"
        verbose_name_plural = "All groups"

    def __str__(self):
        return f"{self.pk} {self.group_name}_{self.faculty} ({self.head_teacher})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        group_name = ["A", "B", "C", "D"]
        faculty = [
            "Dept. of IT",
            "Department of Biology",
            "Dept. of Chemistry",
            "Dept. of Physics",
            "Dept. of PE",
        ]

        for _ in range(count):
            cls.objects.create(
                group_name=random.choice(group_name),
                amount_students=random.randint(24, 33),
                head_teacher=f"{faker.first_name()}_{faker.last_name()}",
                faculty=random.choice(faculty),
                head_teacher_email=faker.email(),
                head_teacher_phone=faker.phone_number(),
            )

src/groups/forms.py
from django import forms

from groups.models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = (
            "group_name",
            "amount_students",
            "head_teacher",
            "faculty",
            "head_teacher_email",
            "head_teacher_phone",
        )

    def clean_group_name(self):
        group_name = self.cleaned_data["group_name"].upper()
        return group_name

    def clean_faculty(self):
        faculty = self.cleaned_data["faculty"].capitalize()
        return faculty


class GroupAdminForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

    comments = forms.CharField(required=False, widget=forms.Textarea)
    email = forms.EmailField()
    send_email = forms.BooleanField()

    def save(self, commit=True):
        print(self.cleaned_data["email"])
        return super().save(commit=commit)

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy

from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView

from webargs import fields

from webargs.djangoparser import use_kwargs

from groups.forms import GroupForm

from groups.models import Group


class GetGroupView(LoginRequiredMixin, TemplateView):
    template_name = "groups/groups_list.html"
    model = Group

    @use_kwargs(
        {
            "group_name": fields.Str(required=False),
            "faculty": fields.Str(required=False),
            "search_text": fields.Str(required=False),
        },
        location="query",
    )
    def get(self, request, **kwargs):
        groups = Group.objects.all()

        search_fields = ["group_name", "faculty", "head_teacher"]

        for field_name, field_value in kwargs.items():
            if field_name == "search_text":
                or_filter = Q()

                for field in search_fields:
                    or_filter |= Q(**{f"{field}__contains": field_value})

                groups = groups.filter(or_filter)

            else:
                if field_value:
                    groups = groups.filter(**{field_name: field_value})

        return render(request, template_name="groups/groups_list.html", context={"groups": groups})


class CreateGroupView(LoginRequiredMixin, CreateView):
    template_name = "groups/group_create.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")
    queryset = Group.objects.all()


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    template_name = "groups/groups_update.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")
    queryset = Group.objects.all()


class DeleteGroupView(LoginRequiredMixin, UpdateView, DeleteView):
    template_name = "groups/groups_delete.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")
    queryset = Group.objects.all()


class GetGroupsTeachersView(LoginRequiredMixin, TemplateView):
    template_name = "groups/groups_teachers.html"
    model = Group

    def get(self, request, pk):
        group = get_object_or_404(Group.objects.all(), pk=pk)

        return render(request, template_name="groups/groups_teachers.html", context={"group": group})

src/templates/groups/group_create.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button  type="submit" class="my-button btn-shine" value="Create">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/groups/groups_delete.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}



{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button class="my-button btn-shine" type="submit" value="Delete">Delete</button>
        </form>
    </div>
{% endblock %}

src/templates/groups/groups_list.html
{% extends "index.html" %}
{% load static %}



{% block content %}

<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <table class="table table-bordered border-primary">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Group name</th>
            <th scope="col">Amount students</th>
            <th scope="col">Head teacher</th>
            <th scope="col">Faculty</th>
            <th scope="col">Head teacher email</th>
            <th scope="col">Head teacher phone</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <th><img src="
                    {% static 'img/avatar3.png' %}" width="35" height="36"  alt="..."
                ></th>
                <th>{{ group.group_name }}</th>
                <th>{{ group.amount_students }}</th>
                <th>{{ group.head_teacher }}</th>
                <th>{{ group.faculty }}</th>
                <th>{{ group.head_teacher_email }}</th>
                <th>{{ group.head_teacher_phone }}</th>
                 <th>
                    <a type="button" class="btn btn-primary"
                       href="{% url 'groups:update_group' group.pk %}">Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                    href="{% url 'groups:delete_group' group.pk %}">Delete</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/templates/groups/groups_teachers.html
{% extends "index.html" %}
{% load static %}


{% block content %}

<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <table class="table table-bordered border-primary">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Group name</th>
            <th scope="col">Amount students</th>
            <th scope="col">Head teacher</th>
            <th scope="col">Faculty</th>
            <th scope="col">Head teacher email</th>
            <th scope="col">Head teacher phone</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th><img src="
                    {% static 'img/avatar3.png' %}" width="35" height="36"  alt="..."
                ></th>
            <th>{{ group.group_name }}</th>
            <th>{{ group.amount_students }}</th>
            <th>{{ group.head_teacher }}</th>
            <th>{{ group.faculty }}</th>
            <th>{{ group.head_teacher_email }}</th>
            <th>{{ group.head_teacher_phone }}</th>
            <th>
                <a type="button" class="btn btn-primary"
                   href="{% url 'groups:update_group' group.pk %}">Edit</a>
            </th>
            <th>
                <a type="button" class="btn btn-danger"
                    href="{% url 'groups:delete_group' group.pk %}">Delete</a>
            </th>
        </tr>
        </tbody>
    </table>
{% endblock %}

src/templates/groups/groups_update.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}

<link href="{% static 'css/button.css' %}" rel="stylesheet">
<link href="{% static 'css/index_card.css' %}" rel="stylesheet">
    <div>
        <form method='POST' style="width: 18em; align-content: center; margin: auto">
            {% csrf_token %}
            {{ form|crispy }}<br>
            <button class="my-button btn-shine" type="submit" value="Update">Update</button>
        </form>
    </div>
{% endblock %}